# Generated by Django 5.2.15 on 2026-06-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_geocoded', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='stations_fu_state_64a61f_idx'), models.Index(fields=['is_geocoded'], name='stations_fu_is_geoc_190735_idx')],
            },
        ),
    ]
