# Generated by Django 5.2.15 on 2026-06-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='stations_fu_is_geoc_190735_idx',
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='fuelstation',
            constraint=models.UniqueConstraint(fields=('opis_id',), name='uniq_fuelstation_opis_id'),
        ),
    ]
